export {Inst} from './inst'
export {Logo} from './logo'
export {VK} from './vk'
export {Men} from './men'
export {Youtube} from './youtube'
export {Twitter} from './twitter'
export {Image1} from './image1'
export {Image2} from './image2'
export {Galka} from './galka'
export {UserIcon}from'./user-icon'

